spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: company
      username: root
      password: rootpassword
      authentication-database: admin
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/company?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: user
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: ${path.changelog:changeLog.xml}
    enabled: true
